package http

import (
	"time"
)

// CredentialResponse is generated by the IAM handler.
type CredentialResponse struct {
	AccessKeyID     string `json:"AccessKeyId"`
	Code            string
	Expiration      time.Time
	LastUpdated     time.Time
	SecretAccessKey string
	Token           string
	Type            string
}
